# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loadtest.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'loadtest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eloadtest.proto\x12\rkeyvaluestore\"\'\n\x07Request\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05\x62lock\x18\x02 \x01(\x03\"\x19\n\x08Response\x12\r\n\x05token\x18\x01 \x01(\t2E\n\x08LoadTest\x12\x39\n\x04\x43\x61ll\x12\x16.keyvaluestore.Request\x1a\x17.keyvaluestore.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loadtest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=33
  _globals['_REQUEST']._serialized_end=72
  _globals['_RESPONSE']._serialized_start=74
  _globals['_RESPONSE']._serialized_end=99
  _globals['_LOADTEST']._serialized_start=101
  _globals['_LOADTEST']._serialized_end=170
# @@protoc_insertion_point(module_scope)
