# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loadtester.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'loadtester.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10loadtester.proto\x12\nloadtester\"\'\n\x07Request\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05\x62lock\x18\x02 \x01(\x03\"\x19\n\x08Response\x12\r\n\x05token\x18\x01 \x01(\t2A\n\nLoadTester\x12\x33\n\x04\x43\x61ll\x12\x13.loadtester.Request\x1a\x14.loadtester.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loadtester_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=32
  _globals['_REQUEST']._serialized_end=71
  _globals['_RESPONSE']._serialized_start=73
  _globals['_RESPONSE']._serialized_end=98
  _globals['_LOADTESTER']._serialized_start=100
  _globals['_LOADTESTER']._serialized_end=165
# @@protoc_insertion_point(module_scope)
